//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adonet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        public int Id { get; set; }
        public string urunAd { get; set; }
        public string urunAciklama { get; set; }
        public string resimYol { get; set; }
        public Nullable<int> begeniSayisi { get; set; }
        public Nullable<int> kategoriId { get; set; }
    
        public virtual kategori kategori { get; set; }
    }
}
