//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adonet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorum
    {
        public int Id { get; set; }
        public string yorumBaslik { get; set; }
        public string yorumDetay { get; set; }
        public Nullable<int> kullaniciId { get; set; }
        public Nullable<System.DateTime> yorumTarih { get; set; }
        public Nullable<bool> onay { get; set; }
    
        public virtual kullanici kullanici { get; set; }
    }
}
